name: Flask Test

on: [push, pull_request]  # 触发事件

jobs:
  test:
    runs-on: ubuntu-latest  # 使用 GitHub 托管的 Ubuntu 运行器

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 拉取代码

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"  # 指定 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -v test_app.py  # 运行单元测试
